# Site settings
title: codemonkeyz | Coding & Life
description: "A simple blog about code, software team management, entrepreneurship and coffee"
url: "https://codemonkeyz.com"
author:
  name: "Daniel Shir"
  email: "daniel@codemonkeyz.com"
  url: "https://codemonkeyz.com"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

jekyll-crosspost_to_medium:
  enabled: true
  text: '<p><i>This was originally posted on <a href="https://codemonkeyz.com">codemonkeyz.com</a></i></p>' 

google_analytics: UA-97378945-1