# Site settings
title: codemonkeyz | Coding & Life
description: "A simple blog about code, software team management, entrepreneurship and coffee"
url: "http://codemonkeyz.com"
author:
  name: "Daniel Shir"
  email: "daniel@codemonkeyz.com"
  url: "http://codemonkeyz.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
